import Hero from "@/components/Hero";
import Features from "@/components/Features";
import SocialProofBand from "@/components/SocialProofBand";
import HowItWorks from "@/components/HowItWorks";
import SamplePreviews from "@/components/SamplePreviews";
import PricingPreview from "@/components/PricingPreview";
import CTASection from "@/components/CTASection";
import JsonLd from "@/components/JsonLd";

/**
 * The original home page composition, preserved verbatim behind the
 * USE_NEW_HOMEPAGE flag in app/page.tsx so we can revert instantly.
 * Do not edit this file while the redesign is in progress — make new
 * design changes in NewHomePage.tsx.
 */

const organizationSchema = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Macrolight Builder",
  url: "https://macrolight-builder.com",
  logo: "https://macrolight-builder.com/logo.png",
  description:
    "We build, host, and manage high-converting websites that turn visitors into paying customers for local businesses.",
  founder: [
    { "@type": "Person", name: "Bradley Bayley" },
    { "@type": "Person", name: "Nick Ottoy" },
  ],
  address: {
    "@type": "PostalAddress",
    streetAddress: "1902 Villa Rd",
    addressLocality: "Birmingham",
    addressRegion: "MI",
    postalCode: "48009",
    addressCountry: "US",
  },
  telephone: "+1-248-214-7957",
  contactPoint: {
    "@type": "ContactPoint",
    contactType: "sales",
    telephone: "+1-248-214-7957",
    url: "https://macrolight-builder.com/contact",
  },
  sameAs: [],
};

const localBusinessSchema = {
  "@context": "https://schema.org",
  "@type": "ProfessionalService",
  name: "Macrolight Builder",
  url: "https://macrolight-builder.com",
  description:
    "Client acquisition websites for local businesses — built, hosted, and managed so your phone rings more every month.",
  priceRange: "$$",
  telephone: "+1-248-214-7957",
  address: {
    "@type": "PostalAddress",
    streetAddress: "1902 Villa Rd",
    addressLocality: "Birmingham",
    addressRegion: "MI",
    postalCode: "48009",
    addressCountry: "US",
  },
  areaServed: {
    "@type": "Country",
    name: "United States",
  },
  serviceType: [
    "Web Design",
    "Web Development",
    "SEO",
    "Lead Generation",
    "CRM Integration",
  ],
};

export default function OldHomePage() {
  return (
    <>
      <JsonLd data={organizationSchema} />
      <JsonLd data={localBusinessSchema} />
      <Hero />
      <SamplePreviews />
      <SocialProofBand />
      <HowItWorks />
      <Features />
      <PricingPreview />
      <CTASection />
    </>
  );
}
